const meta={boots:{name:'Сапоги',desc:'Цельнолитые сапоги для сырой земли и снега. Тёплый вкладыш не заменяет цепкую подошву: на льду нужны отдельные ледоступы.'},jackets:{name:'Куртки',desc:'Рабочие утеплённые модели для холода и софтшелл для активной работы осенью. Выбирайте с запасом на средний слой.'},pants:{name:'Брюки',desc:'Рабочие брюки с флисом и синтепоном. Для работы на коленях полезны усиления; наличие флиса само по себе не означает защиту от дождя.'},hats:{name:'Шапки',desc:'Демисезонный флис для движения и вязаные модели с подкладкой для холода. Размер головы и защита ушей важнее надписи «зимняя».'},gloves:{name:'Перчатки',desc:'Рабочие перчатки для инструмента и утеплённые для прогулок. У покрытия на ладони и защиты от воды разные задачи.'},galoshes:{name:'Галоши',desc:'Утеплённые галоши для частых выходов во двор. Проверены размеры 43, 44 и 45; длину стельки с подкладкой сверяйте отдельно.'},clogs:{name:'Сабо и тапочки',desc:'Чтобы быстро надеть и снять: утеплённые сабо и лёгкие летние варианты. Открытая пятка удобна у двери, но пропускает снег.'}};
let category='galoshes',topOnly=false;const grid=document.getElementById('grid'),dialog=document.getElementById('details');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rub=v=>new Intl.NumberFormat('ru-RU').format(v)+' ₽';
const checked=p=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'short',timeStyle:'short'}).format(new Date(p.checkedAt))+' МСК';
const availability=p=>`<div class="availability">В наличии${p.requiredSizes.length?' · '+p.requiredSizes.join(' / '):''}</div>`;
const wb=p=>`https://www.wildberries.ru/catalog/${p.id}/detail.aspx`;
function rating(p){return p.rating?`<span class="star" aria-label="Оценка">★</span> <b>${esc(p.rating)}</b> <span>· ${p.count} оценок группы</span>`:'<span>Нет доступной оценки</span>'}
document.getElementById('total').textContent=CATALOG.length;
document.getElementById('categories').innerHTML=Object.entries(meta).map(([key,m])=>`<button data-category="${key}" class="${key===category?'active':''}" aria-pressed="${key===category}">${m.name}<span class="count">${CATALOG.filter(p=>p.category===key).length}</span></button>`).join('');
function render(){const query=document.getElementById('search').value.trim().toLowerCase(),sort=document.getElementById('sort').value;let rows=CATALOG.filter(p=>p.category===category&&(!topOnly||p.rank)&&`${p.name} ${p.brand}`.toLowerCase().includes(query));rows.sort((a,b)=>sort==='price'?a.price-b.price:sort==='rating'?(Number(b.rating)||0)-(Number(a.rating)||0):sort==='reviews'?b.count-a.count:(a.rank||99)-(b.rank||99));document.getElementById('categoryDescription').textContent=meta[category].desc;document.getElementById('results').textContent=`Найдено: ${rows.length}`;document.getElementById('empty').hidden=!!rows.length;grid.innerHTML=rows.map(p=>`<article class="card"><div class="card-media"><img src="assets/products/${p.id}.webp" alt="${esc(p.brand+' '+p.name)}" loading="lazy" width="350" height="260">${p.rank?`<span class="pick-badge">МОЙ ВЫБОР № ${p.rank}</span>`:''}</div><div class="card-body"><p class="brand">${esc(p.brand)}</p><h3>${esc(p.name)}</h3><div class="rating">${rating(p)}</div><p class="card-use">${esc(p.use)}</p>${availability(p)}<div class="budget"><b>${p.priceMax>p.price?"от ":""}${rub(p.price)}</b><br><small>Без WB Кошелька · ${checked(p)}</small></div><div class="points"><p class="plus">${esc(p.pros[0])}</p><p class="minus">${esc(p.cons[0])}</p></div><p class="review-peek">${esc(p.reviewSummary)}</p><div class="card-actions"><button data-detail="${p.id}" aria-label="Отзывы и подробности: ${esc(p.name)}">Отзывы и детали</button><a href="${wb(p)}" target="_blank" rel="noopener noreferrer">Посмотреть на WB</a></div></div></article>`).join('')}
document.getElementById('categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;for(const x of document.querySelectorAll('[data-category]')){x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)}render()});
function changeView(value){topOnly=value;document.getElementById('allView').classList.toggle('selected',!value);document.getElementById('topView').classList.toggle('selected',value);document.getElementById('allView').setAttribute('aria-pressed',!value);document.getElementById('topView').setAttribute('aria-pressed',value);render()}
document.getElementById('allView').onclick=()=>changeView(false);document.getElementById('topView').onclick=()=>changeView(true);document.getElementById('search').addEventListener('input',render);document.getElementById('sort').addEventListener('change',render);
grid.addEventListener('click',e=>{const button=e.target.closest('[data-detail]');if(!button)return;const p=CATALOG.find(x=>x.id===Number(button.dataset.detail));document.getElementById('detailContent').innerHTML=`<div class="detail-header"><img src="assets/products/${p.id}.webp" alt="${esc(p.name)}"><div><p class="brand">${esc(p.brand)} · АРТИКУЛ ${p.id}</p><h2>${esc(p.name)}</h2><p>${esc(p.use)}</p><div class="rating">${rating(p)}</div></div></div>${p.rank?`<section class="detail-section"><h3>№ ${p.rank} в моём топе: ${meta[p.category].name.toLowerCase()}</h3><p>${esc(p.reason)}</p></section>`:''}<section class="detail-section"><h3>Плюсы и ограничения</h3><div class="points">${p.pros.map(x=>`<p class="plus">${esc(x)}</p>`).join('')}${p.cons.map(x=>`<p class="minus">${esc(x)}</p>`).join('')}</div><p class="no-review">Это мой вывод по характеристикам и прочитанным отзывам.</p></section><section class="detail-section"><h3>Что пишут покупатели</h3><p>${esc(p.reviewSummary)}</p>${p.quotes.length?p.quotes.map(q=>`<blockquote class="quote"><p>«${esc(q.text)}»</p><cite>Покупатель WB · ${esc(q.date)} · ${q.stars}/5 · артикул ${p.id}</cite></blockquote>`).join(''):'<p class="no-review">Текстовых отзывов именно этого артикула в доступной выгрузке нет. Отзывы других артикулов сюда не перенесены.</p>'}<a class="detail-link" href="${wb(p)}?tab=feedbacks" target="_blank" rel="noopener noreferrer">Карточка и отзывы WB</a></section><section class="detail-section"><h3>Характеристики продавца</h3><dl class="specs">${Object.entries(p.specs).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><p class="no-review">Характеристики и температурные обещания продавца не проверены испытаниями.</p><a class="detail-link" href="${esc(p.cardSource)}" target="_blank" rel="noopener noreferrer">Источник характеристик</a></section><section class="detail-section"><h3>Цена и доступные размеры</h3>${availability(p)}<p>Проверено ${checked(p)} на странице товара WB. Цены без скидки WB Кошелька; окончательная стоимость и доставка — в Вашей карточке WB.</p><div class="offer-list">${p.sizeOffers.map(s=>`<div><b>Размер WB: ${esc(s.ru)}</b><span>Маркировка: ${esc(s.manufacturer)}${s.covers.length?" · подходит по сетке: "+s.covers.join(", "):""}</span><strong>${rub(s.price)}</strong></div>`).join("")}</div><p class="no-review">Учтены только доступные к заказу варианты. Сдвоенный размер покрывает указанные значения сетки, но не гарантирует посадку: сверяйте замеры и ростовку, примеряйте с тёплым слоем. Остатки могут измениться.</p><a class="primary" href="${wb(p)}" target="_blank" rel="noopener noreferrer">Открыть модель на Wildberries</a></section>`;dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0});
dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});dialog.addEventListener('close',()=>document.body.style.overflow='');
document.getElementById('sourceLinks').innerHTML=SOURCES.map(g=>`<div class="source-group"><h3>${esc(g.title)}</h3>${g.links.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>${s.note?`<p class="no-review">${esc(s.note)}</p>`:''}`).join('')}</div>`).join('');render();
